spring.datasource.url=jdbc:postgresql://database-2.cjaw4wow08gu.eu-west-3.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=cheblog6pr
spring.jpa.hibernate.ddl-auto=update

spring.elasticsearch.uris=http://13.37.244.104
spring.elasticsearch.username=
spring.elasticsearch.password=

elasticsearch.index.name=item_details

# Logging
logging.level.com._ach.backend.search=DEBUG